apiVersion: v1
kind: Service
metadata:
  name: parcelgo-api-nodeport
  labels:
    app: parcelgo-api
spec:
  type: NodePort
  selector:
    app: parcelgo-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30090
