name: NovaPay CI (Split Jobs)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      APP_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install & lint
        working-directory: 01-beginner/sample-app
        run: |
          npm install
          npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      APP_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - name: Context
        run: |
          echo "event=${{ github.event_name }}"
          echo "sha=${{ github.sha }}"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install & test
        working-directory: 01-beginner/sample-app
        run: |
          npm install
          npm test
