services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: cicd-bootcamp-jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    group_add:
      - ${DOCKER_GID:-0}

volumes:
  jenkins_home:
